import * as spotify from 'spotify-web-sdk'
import { AuthUrl, getTokenFromUrl } from './Auth'

function App() {

  const generateLikedSongsPlaylist = () => {
    spotify.init({ token: getTokenFromUrl() })

    spotify.getCurrentUserProfile().then(
      user => {
        spotify.createPlaylist(user.id, 'My Liked Songs - Auto-Generated by Spotlike', {
          public: true,
          collaborative: false
        }).then(
          playlist => {
            spotify.getCurrentUserSavedTracks()
            .then(
              likedSongs => {
                let trackUris: string[] = []
                likedSongs.items.forEach(song => trackUris.push(song.track.uri))
                spotify.addTracksToPlaylist(playlist.id, trackUris)
              }
            )
          }
        )
      }
    )
  }

  return (
    <>
      <a href={AuthUrl}>First, login with your Spotify Account</a>
      <hr />
      <button onClick={generateLikedSongsPlaylist}>Generate liked songs playlist</button>
    </>
  )
}

export default App;
